# Generated by Django 5.0.2 on 2025-03-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('active_ingredient', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('last_review_date', models.DateField()),
                ('category', models.CharField(choices=[('Herbicida', 'Herbicida'), ('Fungicida', 'Fungicida'), ('Insecticida', 'Insecticida'), ('Acaricida', 'Acaricida'), ('Otro', 'Otro')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
